version: '3.8'

services:
  spring-app:
#    image: 'swoqe/spring_labs:lab2'
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: spring-app
    depends_on:
      - db
    environment:
      - INITIALIZATION_MODE=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/librarianship
      - SPRING_DATASOURCE_USERNAME=librarianship
      - SPRING_DATASOURCE_PASSWORD=librarianship
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=librarianship
      - APP_DB_PASS=librarianship
      - APP_DB_NAME=librarianship
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"