apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rest-api
  template:
    metadata:
      name: rest-api-pod
      labels:
        component: rest-api
    spec:
      containers:
        - name: rest-api-container
          image: swoqe/librarianship-rest-api
          ports:
            - containerPort: 8080
          env:
            - name: INITIALIZATION_MODE
              value: "true"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://cluster-ipi-service-postgres:5432/librarianship"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: pgpassword
                    key: PGPASSWORD
